var incomeStatement ={"is_operating_revenue":"operating revenue",
"is_total_revenue":"total revenue",
"is_adjustments_to_revenue":"adjustments to revenue",
"is_cost_of_sales":"cost of sales",
"is_cost_of_sales_with_depreciation":"cost of sales with depreciation",
"is_gross_margin":"gross margin",
"is_gross_operating_profit":"gross operating profit",
"is_RD":"Research & Development (R&D) Expense",
"is_SGA":"Selling, General & Administrative (SG&A) Expense",
"is_advertising":"advertising",
"is_operating_income":"operating income",
"is_EBITDA":"EBITDA",
"is_depreciation":"depreciation",
"is_depreciation_two":"depreciation",
"is_amortization":"amortization",
"is_amortization_two":"amortization",
"is_amortization_of_intangibles":"amortization of intangibles",
"is_interest_income":"interest income",
"is_earnings_from_equity_interest":"earnings from equity interest",
"is_other_income_net":"other income net",
"is_income_acquired_in_process_ra":"income, acquired in process r&a",
"is_Income_Restructuring_and_MA":"Income, Restructuring and M&A",
"is_other_special_charges":"other special charges",
"is_special_income_charges":"special income charges",
"is_EBIT":"EBIT",
"is_interest_expense":"interest expense",
"is_income_taxes":"income taxes",
"is_minority_interest":"minority interest",
"is_pref_securities_of_subsid_trust":"pref. securities of subsid. trust",
"is_income_before_income_taxes":"income before income taxes",
"is_net_income_continuing_operations":"net income (continuing operations)",
"is_net_income_discontinued_operations":"net income (discontinued operations)",
"is_net_income_total_operations":"net income (total operations)",
"is_extraordinary_income_losses":"extraordinary income/losses",
"is_income_from_cum_effect_of_acct_change":"income from cum. effect of acct. change",
"is_income_from_tax_loss_carryforward":"income from tax loss carryforward",
"is_other_gains_losses":"other gains/losses",
"is_total_net_income":"total net income",
"is_normalized_income":"normalized income",
"is_net_income_available_for_common":"net income available for common",
"is_preferred_dividends":"preferred dividends",
"is_excise_taxes":"excise taxes"
};

var balanceSheet ={
    "bs_a_cash_equivalents":"cash & equivalents",
"bs_a_restricted_cash":"restricted cash",
"bs_a_marketable_securities":"marketable securities",
"bs_a_accounts_receivable":"accounts receivable",
"bs_a_loans_receivable":"loans receivable",
"bs_a_other_receivable":"other receivable",
"bs_a_receivables":"receivables",
"bs_a_inventories_raw_materials":"inventories, raw materials",
"bs_a_inventories_work_in_progress":"inventories, work in progress",
"bs_a_inventories_purchased_components":"inventories, purchased components",
"bs_a_inventories_finished_goods":"inventories, finished goods",
"bs_a_inventories_other":"inventories, other",
"bs_a_inventories_adjustments_allowances":"inventories, adjustments & allowances",
"bs_a_inventories":"inventories",
"bs_a_prepaid_expenses":"prepaid expenses",
"bs_a_current_defered_income_taxes":"current defered income taxes",
"bs_a_other_current_assets":"other current assets",
"bs_a_total_current_assets":"total current assets",
"bs_a_land_and_improvements":"land and improvements",
"bs_a_building_and_improvements":"building and improvements",
"bs_a_machinery_furniture_equipment":"machinery, furniture & equipment",
"bs_a_construction_in_progress":"construction in progress",
"bs_a_other_fixed_assets":"other fixed assets",
"bs_a_total_fixed_assets":"total fixed assets",
"bs_a_gross_fixed_assets":"gross fixed assets",
"bs_a_accumulated_depreciation":"accumulated depreciation",
"bs_a_net_fixed_assets":"net fixed assets",
"bs_a_intangibles":"intangibles",
"bs_a_cost_in_excess":"cost in excess",
"bs_a_non_current_deferred_income_taxes":"non-current deferred income taxes",
"bs_a_other_non_current_assets":"other non-current assets",
"bs_a_total_non_current_assets":"total non-current assets",
"bs_a_total_assets":"total assets",
"bs_a_inventory_valuation_method":"inventory valuation method",
"bs_l_accounts_payable":"accounts payable",
"bs_l_notes_payable":"notes payable",
"bs_l_short_term_debt":"short-term debt",
"bs_l_accrued_expenses":"accrued expenses",
"bs_l_accrued_liabilities":"accrued liabilities",
"bs_l_deferred_revenues":"deferred revenues",
"bs_l_current_deferred_income_taxes":"current deferred income taxes",
"bs_l_other_current_liabilities":"other current liabilities",
"bs_l_total_current_liabilities":"total current liabilities",
"bs_l_long_term_debt":"long-term debt",
"bs_l_capital_lease_obligations":"capital lease obligations",
"bs_l_deferred_income_taxes":"deferred income taxes",
"bs_l_other_non_current_liabilities":"other non-current liabilities",
"bs_l_minority_interest_liability":"minority interest liability",
"bs_l_preferred_secur_of_subsid_trust":"preferred secur. of subsid. trust",
"bs_l_preferred_equity_outside_stock_equity":"preferred equity outside stock equity",
"bs_l_total_non_current_liabilities":"total non-current liabilities",
"bs_l_total_liabilities":"total liabilities",
"bs_l_preferred_stock_equity":"preferred stock equity",
"bs_l_common_stock_equity":"common stock equity",
"bs_l_common_par":"common par",
"bs_l_additional_paid_in_capital":"additional paid-in capital",
"bs_l_cumulative_translation_adjustments":"cumulative translation adjustments",
"bs_l_retained_earnings":"retained earnings",
"bs_l_treasury_stock":"treasury stock",
"bs_l_other_equity_adjustments":"other equity adjustments",
"bs_l_total_capitalization":"total capitalization",
"bs_l_total_equity":"total equity",
"bs_l_total_liabilities_stock_equity":"total liabilities & stock equity"  
};



var cashFlow={
    "cf_o_net_income_loss":"net income/loss",
"cf_o_depreciation":"depreciation",
"cf_o_amortization":"amortization",
"cf_o_amortization_of_intangibles":"amortization of intangibles",
"cf_o_deferred_income_taxes":"deferred income taxes",
"cf_o_operating_gains":"operating gains",
"cf_o_extraordinary_gains":"extraordinary gains",
"cf_o_increase_decrease_in_receivables":"(increase) decrease in receivables",
"cf_o_increase_decrease_in_inventories":"(increase) decrease in inventories",
"cf_o_increase_decrease_in_prepaid_expenses":"(increase) decrease in prepaid expenses",
"cf_o_increase_decrease_in_other_current_assets":"(increase) decrease in other current assets",
"cf_o_decrease_increase_in_payables":"decrease (increase) in payables",
"cf_o_decrease_increase_in_other_current_liabilities":"decrease (increase) in other current liabilities",
"cf_o_decrease_increase_in_other_working_capital":"decrease (increase) in other working capital",
"cf_o_other_non_cash_items":"other non-cash items",
"cf_o_net_cash_from_continuing_operations":"net cash from continuing operations",
"cf_o_net_cash_from_discontinued_operations":"net cash from discontinued operations",
"cf_o_net_cash_from_total_operating_activities":"net cash from total operating activities",
"cf_i_sale_of_property_plant_equipment":"sale of property, plant & equipment",
"cf_i_sale_of_long_term_investments":"sale of long-term investments",
"cf_i_sale_of_short_term_investments":"sale of short-term investments",
"cf_i_purchase_of_property_plant_equipment":"purchase of property, plant & equipment",
"cf_i_acquisitions":"acquisitions",
"cf_i_purchase_of_long_term_investments":"purchase of long-term investments",
"cf_i_other_investing_changes_net":"other investing changes, net",
"cf_i_cash_from_discontinued_investing_activities":"cash from discontinued investing activities",
"cf_i_net_cash_from_investing_activities":"net cash from investing activities",
"cf_f_issuance_of_debt":"issuance of debt",
"cf_f_issuance_of_capital_stock":"issuance of capital stock",
"cf_f_repayment_of_long_term_debt":"repayment of long-term debt",
"cf_f_repurchase_of_capital_stock":"repurchase of capital stock",
"cf_f_payment_of_cash_dividends":"payment of cash dividends",
"cf_f_other_financing_charges_net":"other financing charges, net",
"cf_f_cash_from_discontinued_financing_activities":"cash from discontinued financing activities",
"cf_f_net_cash_from_financing_activities":"net cash from financing activities",
"cf_net_effect_exchange_rate_changes":"effect exchange rate changes",
"cf_net_net_change_in_cash_equivalents":"net change in cash & equivalents",
"cf_net_cash_at_beginning_of_period":"cash at beginning of period",
"cf_net_cash_end_of_period":"cash end of period"  
};

var ratios={
    "r_profit_margins_Close_PE_Ratio":"Close PE Ratio",
"r_profit_margins_High_PE_Ratio":"High PE Ratio",
"r_profit_margins_Low_PE_Ratio":"Low PE Ratio",
"r_profit_margins_gross_profit_margin":"gross profit margin",
"r_profit_margins_pre_tax_profit_margin":"pre-tax profit margin",
"r_profit_margins_post_tax_profit_margin":"post-tax profit margin",
"r_profit_margins_net_profit_margin":"net profit margin",
"r_profit_margins_interest_coverage_cont_operations":"interest coverage (cont. operations)",
"r_profit_margins_interest_as_perc_of_invested_capital":"interest as % of invested capital",
"r_profit_margins_effective_tax_rate":"effective tax rate",
"r_profit_margins_income_per_employee":"income per employee",
"r_normalized_Normalized_Close_PE_Ratio":"Normalized Close PE Ratio",
"r_normalized_Normalized_High_PE_Ratio":"Normalized High PE Ratio",
"r_normalized_Normalized_Low_PE_Ratio":"Normalized Low PE Ratio",
"r_normalized_normalized_net_profit_margin":"normalized net profit margin",
"r_normalized_Normalized_ROE":"Normalized ROE",
"r_normalized_Normalized_ROA":"Normalized ROA",
"r_normalized_Normalized_ROCI":"Normalized ROCI",
"r_normalized_normalized_income_per_employee":"normalized income per employee",
"r_solvency_quick_ratio":"quick ratio",
"r_solvency_current_ratio":"current ratio",
"r_solvency_payout_ratio":"payout ratio",
"r_solvency_total_debt_equity_ratio":"total debt/equity ratio",
"r_efficiency_leverage_ratio":"leverage ratio",
"r_efficiency_asset_turnover":"asset turnover",
"r_efficiency_cash_as_perc_of_revenue":"cash as % of revenue",
"r_efficiency_receivables_as_perc_of_revenue":"receivables as % of revenue",
"r_efficiency_SGA_as_perc_of_Revenue":"SG&A as % of Revenue",
"r_efficiency_RD_as_perc_of_Revenue":"R&D as % of Revenue",
"r_activity_revenue_per_dollar_cash":"revenue per $ cash",
"r_activity_revenue_per_dollar_common_equity":"revenue per $ common equity",
"r_activity_revenue_per_dollar_invested_capital":"revenue per $ invested capital",
"r_activity_receivables_turnover":"receivables turnover",
"r_activity_inventory_turnover":"inventory turnover",
"r_liquidity_receivables_per_day_sales":"receivables per day sales",
"r_liquidity_sales_per_dollar_receivables":"sales per $ receivables",
"r_liquidity_sales_per_dollar_inventory":"sales per $ inventory",
"r_liquidity_revenue_assets":"revenue/assets",
"r_liquidity_number_of_days_cost_of_goods_in_inventory":"number of days cost of goods in inventory",
"r_liquidity_current_assets_per_share":"current assets per share",
"r_liquidity_total_assets_per_share":"total assets per share",
"r_liquidity_intangibles_as_perc_of_book_value":"intangibles as % of book-value",
"r_liquidity_inventory_as_perc_of_revenue":"inventory as % of revenue",
"r_capital_structure_long_term_debt_per_share":"long-term debt per share",
"r_capital_structure_current_liabilities_per_share":"current liabilities per share",
"r_capital_structure_cash_per_share":"cash per share",
"r_capital_structure_LT_Debt_to_Equity_Ratio":"LT-Debt to Equity Ratio",
"r_capital_structure_LT_Debt_as_perc_of_Invested_Capital":"LT-Debt as % of Invested Capital",
"r_capital_structure_LT_Debt_as_perc_of_Total_Debt":"LT-Debt as % of Total Debt",
"r_capital_structure_total_debt_as_perc_total_assets":"total debt as % total assets",
"r_capital_structure_working_captial_as_perc_of_equity":"working captial as % of equity",
"r_capital_structure_revenue_per_share":"revenue per share",
"r_capital_structure_book_value_per_share":"book value per share",
"r_capital_structure_tangible_book_value_per_share":"tangible book value per share",
"r_capital_structure_price_revenue_ratio":"price/revenue ratio",
"r_capital_structure_price_equity_ratio":"price/equity ratio",
"r_capital_structure_price_tangible_book_ratio":"price/tangible book ratio",
"r_capital_structure_working_capital_as_perc_of_price":"working capital as % of price",
"r_profitability_working_capital_per_share":"working capital per share",
"r_profitability_cash_flow_per_share":"cash flow per share",
"r_profitability_free_cash_flow_per_share":"free cash flow per share",
"r_profitability_Return_on_Stock_Equity_ROE":"Return on Stock Equity (ROE)",
"r_profitability_Return_on_Capital_Invested_ROCI":"Return on Capital Invested (ROCI)",
"r_profitability_Return_on_Assets_ROA":"Return on Assets (ROA)",
"r_profitability_price_cash_flow_ratio":"price/cash flow ratio",
"r_profitability_price_free_cash_flow_ratio":"price/free cash flow ratio",
"r_profitability_sales_per_employee":"sales per employee",
"r_against_industry_perc_of_sales_to_industry":"% of sales-to-industry",
"r_against_industry_perc_of_earnings_to_industry":"% of earnings-to-industry",
"r_against_industry_perc_of_EPS_to_Industry":"% of EPS-to-Industry",
"r_against_industry_perc_of_price_to_industry":"% of price-to-industry",
"r_against_industry_perc_of_PE_to_Industry":"% of PE-to-Industry",
"r_against_industry_perc_of_price_book_to_industry":"% of price/book-to-industry",
"r_against_industry_perc_of_price_sales_to_industry":"% of price/sales-to-industry",
"r_against_industry_perc_of_price_cashflow_to_industry":"% of price/cashflow-to-industry",
"r_against_industry_perc_of_pric_free_cashlow_to_industry":"% of pric/free cashlow-to-industry",
"r_against_industry_perc_of_debt_equity_to_industry":"% of debt/equity-to-industry",
"r_against_industry_perc_of_current_ratio_to_industry":"% of current ratio-to-industry",
"r_against_industry_perc_of_gross_profit_margin_to_industry":"% of gross profit margin-to-industry",
"r_against_industry_perc_of_pre_tax_profit_margin_to_industry":"% of pre-tax profit margin-to-industry",
"r_against_industry_perc_of_post_tax_profit_margin_to_industry":"% of post-tax profit margin-to-industry",
"r_against_industry_perc_of_net_profit_margin_to_industry":"% of net profit margin-to-industry",
"r_against_industry_perc_of_ROE_to_Industry":"% of ROE-to-Industry",
"r_against_industry_perc_of_leverage_to_industry":"% of leverage-to-industry"
};

